USE [master]
GO
/****** Object:  Database [VidaFitMarket]    Script Date: 06/06/2026 21:49:28 ******/
CREATE DATABASE [VidaFitMarket]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VidaFitMarket', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VidaFitMarket.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VidaFitMarket_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VidaFitMarket_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [VidaFitMarket] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VidaFitMarket].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VidaFitMarket] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VidaFitMarket] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VidaFitMarket] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VidaFitMarket] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VidaFitMarket] SET ARITHABORT OFF 
GO
ALTER DATABASE [VidaFitMarket] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VidaFitMarket] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VidaFitMarket] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VidaFitMarket] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VidaFitMarket] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VidaFitMarket] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VidaFitMarket] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VidaFitMarket] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VidaFitMarket] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VidaFitMarket] SET  ENABLE_BROKER 
GO
ALTER DATABASE [VidaFitMarket] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VidaFitMarket] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VidaFitMarket] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VidaFitMarket] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VidaFitMarket] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VidaFitMarket] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VidaFitMarket] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VidaFitMarket] SET RECOVERY FULL 
GO
ALTER DATABASE [VidaFitMarket] SET  MULTI_USER 
GO
ALTER DATABASE [VidaFitMarket] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VidaFitMarket] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VidaFitMarket] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VidaFitMarket] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VidaFitMarket] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VidaFitMarket] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'VidaFitMarket', N'ON'
GO
ALTER DATABASE [VidaFitMarket] SET QUERY_STORE = ON
GO
ALTER DATABASE [VidaFitMarket] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [VidaFitMarket]
GO
/****** Object:  Table [dbo].[Administrador]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Administrador](
	[id_admin] [int] IDENTITY(1,1) NOT NULL,
	[correo] [varchar](100) NULL,
	[nombre] [varchar](100) NULL,
	[contraseña] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_admin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Blog]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blog](
	[id_blog] [int] IDENTITY(1,1) NOT NULL,
	[id_admin] [int] NULL,
	[titulo] [varchar](200) NULL,
	[contenido] [text] NULL,
	[fecha_publicacion] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_blog] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Detalle_pedido]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Detalle_pedido](
	[id_detalle] [int] IDENTITY(1,1) NOT NULL,
	[id_pedido] [int] NULL,
	[id_producto] [int] NULL,
	[cantidad] [int] NULL,
	[subtotal] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_detalle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mascota]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mascota](
	[id_mascota] [int] IDENTITY(1,1) NOT NULL,
	[id_usuario] [int] NULL,
	[nombre] [varchar](100) NULL,
	[raza] [varchar](100) NULL,
	[edad] [int] NULL,
	[peso] [decimal](5, 2) NULL,
	[necesidad] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_mascota] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedido]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedido](
	[id_pedido] [int] IDENTITY(1,1) NOT NULL,
	[id_usuario] [int] NULL,
	[total] [decimal](10, 2) NULL,
	[estado] [varchar](50) NULL,
	[fecha] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_pedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[id_producto] [int] IDENTITY(1,1) NOT NULL,
	[id_admin] [int] NULL,
	[nombre] [varchar](100) NULL,
	[categoria] [varchar](100) NULL,
	[precio] [decimal](10, 2) NULL,
	[stock] [int] NULL,
	[descripcion] [varchar](300) NULL,
	[beneficio] [varchar](200) NULL,
	[tipo_usuario] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recomendacion]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recomendacion](
	[id_recomendacion] [int] IDENTITY(1,1) NOT NULL,
	[id_usuario] [int] NULL,
	[id_mascota] [int] NULL,
	[id_producto] [int] NULL,
	[objetivo] [varchar](100) NULL,
	[actividad] [varchar](100) NULL,
	[necesidad] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_recomendacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 06/06/2026 21:49:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NULL,
	[correo] [varchar](100) NULL,
	[contraseña] [varchar](100) NULL,
	[telefono] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Blog]  WITH CHECK ADD FOREIGN KEY([id_admin])
REFERENCES [dbo].[Administrador] ([id_admin])
GO
ALTER TABLE [dbo].[Detalle_pedido]  WITH CHECK ADD FOREIGN KEY([id_pedido])
REFERENCES [dbo].[Pedido] ([id_pedido])
GO
ALTER TABLE [dbo].[Detalle_pedido]  WITH CHECK ADD FOREIGN KEY([id_producto])
REFERENCES [dbo].[Producto] ([id_producto])
GO
ALTER TABLE [dbo].[Mascota]  WITH CHECK ADD FOREIGN KEY([id_usuario])
REFERENCES [dbo].[Usuario] ([id_usuario])
GO
ALTER TABLE [dbo].[Pedido]  WITH CHECK ADD FOREIGN KEY([id_usuario])
REFERENCES [dbo].[Usuario] ([id_usuario])
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([id_admin])
REFERENCES [dbo].[Administrador] ([id_admin])
GO
ALTER TABLE [dbo].[Recomendacion]  WITH CHECK ADD FOREIGN KEY([id_mascota])
REFERENCES [dbo].[Mascota] ([id_mascota])
GO
ALTER TABLE [dbo].[Recomendacion]  WITH CHECK ADD FOREIGN KEY([id_producto])
REFERENCES [dbo].[Producto] ([id_producto])
GO
ALTER TABLE [dbo].[Recomendacion]  WITH CHECK ADD FOREIGN KEY([id_usuario])
REFERENCES [dbo].[Usuario] ([id_usuario])
GO
USE [master]
GO
ALTER DATABASE [VidaFitMarket] SET  READ_WRITE 
GO
